export {default as Pic1} from '../images/pic1.webp'
export {default as Pic2} from '../images/pic2.webp'
export {default as Pic3} from '../images/pic3.webp'
export {default as Pic4} from '../images/pic4.webp'
export {default as Pic5} from '../images/pic5.webp'